[package]
name = "mirage"
version = "0.1.0"
authors = ["Nathan Stocks <nathan.stocks@gmail.com>", "Chris Milbert"]
edition = "2018"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
image = "0.24.3"
num-complex = "0.4.2"
